services:
    sineflow.clamav.scanner:
        class: Sineflow\ClamAV\Scanner
        factory: ['Sineflow\ClamAV\Bundle\ScannerFactory', createScanner]
        arguments:
            - '%sineflow.clamav%'
        public: true

    Sineflow\ClamAV\Scanner: '@sineflow.clamav.scanner'
